# properties used by integration tests
spring:
  datasource:
    url: jdbc:h2:mem:service;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password:
    driverClassName: org.h2.Driver
  cache:
    type: none
  jpa:
    hibernate:
      ddl-auto: none
  test:
    database:
      replace: none